apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus/prometheus-config.yaml
  - prometheus/prometheus-deployment.yaml
  - grafana/grafana-deployment.yaml
  - alertmanager/alertmanager-deployment.yaml

commonLabels:
  project: ait-core
  managed-by: kustomize

images:
  - name: prom/prometheus
    newTag: v2.48.0
  - name: grafana/grafana
    newTag: 10.2.0
  - name: prom/alertmanager
    newTag: v0.26.0
